# -*- yaml -*-
# Codeface configuration for Jenkins (https://www.jenkins.io/)
# Copyright 2025, Nicole Hoess <nicole.hoess@oth-regensburg.de>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

---
project: jenkins
repo: jenkins    # https://github.com/jenkinsci/jenkins.git
description: Jenkins
revisions: [ ]
rcs: [ ]
tagging: file
windowSize: 6

# Complexity analysis settings
sloccount: true
understand: false