# -*- yaml -*-
# Codeface configuration for AngularJS (https://angularjs.org/)
# Copyright 2025, Nicole Hoess <nicole.hoess@oth-regensburg.de>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

---
project: angular_js_bug
repo: angular_js_bug    # https://github.com/angular/angular.js
description: AngularJS
revisions: [ ]
rcs: [ ]
tagging: file
windowSize: 6

# Complexity analysis settings
sloccount: true
understand: false
