# -*- yaml -*-
# Codeface configuration for Django (https://www.djangoproject.com/)
# Copyright 2025, Nicole Hoess <nicole.hoess@oth-regensburg.de>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

---
project: netxms
repo: netxms     # https://github.com/netxms/netxms.git
description: netxms
revisions: [ ]
rcs: [ ]
tagging: proximity
windowSize: 9

# Complexity analysis settings
sloccount: true
understand: false