# -*- yaml -*-
# Codeface configuration for RStudio (https://spark.apache.org/)
# Copyright 2025, Nicole Hoess <nicole.hoess@oth-regensburg.de>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

---
project: spark
repo: spark        # https://github.com/apache/spark
description: Spark
revisions: [ ]
rcs: [ ]
tagging: proximity
windowSize: 3

# Complexity analysis settings
sloccount: true
understand: false