# SPDX-FileCopyrightText: 2025 OTH Regensburg, Nicole Hoess <nicole.hoess@othr.de>
# SPDX-License-Identifier: GPL-2.0-only

dir.create(Sys.getenv("R_LIBS_USER"), recursive = TRUE)

install.packages("devtools", dependencies=TRUE)
install.packages("progress", dependencies=TRUE)
install.packages("conflicted", dependencies=TRUE)
install.packages("cowplot", dependencies=TRUE)
install.packages("dplyr", dependencies=TRUE)
install.packages("formattable", dependencies=TRUE)
install.packages("ggplot2", dependencies=TRUE)
devtools::install_github("teunbrand/ggh4x")
install.packages("network", dependencies=TRUE)
install.packages("sna", dependencies=TRUE)
install.packages("ggnetwork", dependencies=TRUE)
install.packages("ggrepel", dependencies=TRUE)
install.packages("gridExtra", dependencies=TRUE)
install.packages("igraph", dependencies=TRUE)
install.packages("kableExtra", dependencies=TRUE)
install.packages("matrixStats", dependencies=TRUE)
install.packages("patchwork", dependencies=TRUE)
install.packages("qgraph", dependencies=TRUE)
install.packages("scales", dependencies=TRUE)
install.packages("psych", dependencies=TRUE)
install.packages("tidyverse", dependencies=TRUE)
install.packages("TSclust", dependencies=TRUE)
install.packages("this.path", dependencies=TRUE)
install.packages("tikzDevice", dependencies=TRUE)
install.packages("purrr", dependencies=TRUE)
install.packages("broom", dependencies=TRUE)
install.packages("yaml", dependencies=TRUE)
install.packages("texreg", dependencies=TRUE)
install.packages("boot", dependencies=TRUE)
install.packages("RColorBrewer", dependencies=TRUE)
install.packages("htmlTable", dependencies=TRUE)
install.packages("relaimpo", dependencies=TRUE)
install.packages("treemapify", dependencies=TRUE)
install.packages("colorspace", dependencies=TRUE)
install.packages("optparse", dependencies=TRUE)
install.packages("docopt", dependencies=TRUE)
install.packages("ggnewscale", dependencies=TRUE)
install.packages("ggforce", dependencies=TRUE)
