# SPDX-FileCopyrightText: 2025 OTH Regensburg, Nicole Hoess <nicole.hoess@othr.de>
# SPDX-License-Identifier: GPL-2.0-only

# Runs the analysis pipeline with git2net.
# Extracts data from repositories, matches developer identities,
# constructs developer networks and calculates complexity metrics.

import argparse
import csv
import git2net
import igraph
import matplotlib.pyplot as plt
import os
import pandas as pd
import pathpy as pp
import cairo # requires brew install cairo pkg-config
import sqlite3
import yaml

from collections import defaultdict
from datetime import datetime


def arguments():
    """Define command line options."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--conf", required=True,
                        help="Path to the configuration file.")
    parser.add_argument("--network_mode", required=False,
                        help="For git2net, the network format for network metrics "
                             "calculation. Supports edgelist and adjacency.")
    return parser.parse_args()


def get_igraph(t, directed):
    """
    Creates and saves the igraph of the given git2net network.
    Edited from: https://ingoscholtes.github.io/pathpy/tutorial.html.
    """

    if directed:
        t = pp.Network.from_temporal_network(t)
        g = igraph.Graph(directed=True)
    else:
        g = igraph.Graph(directed=False)

    for e in t.edges:
        # Convert author IDs, which are sometimes returned as float, to integer
        # and then to String. This avoids errors when igraph interprets
        # author IDs as node IDs, which are numbered from 0 to n-1.
        dev_1 = e[0]
        dev_2 = e[1]
        if isinstance(dev_1, (int, float)):
            dev_1 = str(int(dev_1))
        if isinstance(dev_2, (int, float)):
            dev_2 = str(int(dev_2))

        # Add new nodes to vertex set.
        if g.vcount() == 0 or dev_1 not in g.vs["name"]:
            g.add_vertex(dev_1)
        if g.vcount() == 0 or dev_2 not in g.vs["name"]:
            g.add_vertex(dev_2)

        g.add_edge(dev_1, dev_2, weight=t.edges[e]["weight"])
    return g


def save_adjacency(g, adjacency_path):
    """
    Creates and saves the adjacency matrix of the given git2net network.
    Edited from: https://ingoscholtes.github.io/pathpy/tutorial.html.
    """
    adj = pd.DataFrame(g.get_adjacency(attribute="weight").data, columns=g.vs["name"], index=g.vs["name"])
    adj.to_csv(adjacency_path, index=True)
    print("Saved adjacency matrix to " + adjacency_path)


def save_edgelist(g, edgelist_path):
    """
    Creates and saves the edge list of the given git2net network.
    Code generated by ChatGPT-
    """
    with open(edgelist_path, mode='w', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(['source', 'target', 'key', 'time'])  # key = unique edge ID or timestamp

        for idx, (u, v, t) in enumerate(g.tedges):
            writer.writerow([u, v, idx, t])

    print("Saved edge list to " + edgelist_path)


def save_graph(g, graph_path):
    fig, ax = plt.subplots(figsize=(10, 10))
    igraph.plot(g,
                target=ax,
                layout="circle",  # print nodes in a circular layout
                vertex_size=15,
                vertex_frame_width=0.0,
                vertex_frame_color="white",
                vertex_label=g.vs["name"],
                vertex_label_size=15.0,
                edge_size=1)
    fig.savefig(graph_path)


def main(project, git_repo_path, analysis_path, block_mode, ranges, network_mode, complexity=False):
    if block_mode:
        network_path = os.path.join(analysis_path, "block")
        sqlite_db_file = os.path.join(analysis_path, project+"_block.db")
    else:
        network_path = os.path.join(analysis_path, "line")
        sqlite_db_file = os.path.join(analysis_path, project+"_line.db")
    coediting_path = os.path.join(network_path, "coediting")
    if not os.path.exists(coediting_path):
        os.makedirs(coediting_path)

    # Perform analysis if no database exists.
    if not os.path.exists(sqlite_db_file):
        # Extract commits.
        git2net.mine_git_repo(git_repo_path,
                              sqlite_db_file,
                              use_blocks=block_mode,
                              no_of_processes=8)

        # Match developer identities.
        git2net.disambiguate_aliases_db(sqlite_db_file)

    # Construct developer network for each time window.
    for i in range(0, len(ranges) - 1):
        start_date = ranges[i] #datetime.strptime(ranges[i], '%Y-%m-%d %H:%M:%S')
        end_date = ranges[i+1] #datetime.strptime(ranges[i + 1], '%Y-%m-%d %H:%M:%S')

        # Co-editing network
        t, node_info, edge_info = git2net.get_coediting_network(sqlite_db_file,
                                                                time_from=start_date, time_to=end_date)
        if len(t.nodes) > 0:
            if network_mode == "edgelist":
                save_edgelist(t, os.path.join(coediting_path, "range_" + str(i + 1) + "_edgelist.csv"))
            else:
                g = get_igraph(t, directed=True)
                save_adjacency(g, os.path.join(coediting_path, "range_" + str(i + 1) + "_adjacency_matrix.csv"))

    # Calculate complexity metrics,
    if complexity:
        git2net.compute_complexity(git_repo_path, sqlite_db_file)


if __name__ == "__main__":
    args = arguments()

    # Configure the analysis run.
    with open(args.conf) as file:
        conf = yaml.safe_load(file)
    project = conf["project"]
    git_repo_path = conf["git_repo_path"]
    analysis_path = conf["analysis_path"]
    ranges = conf["ranges"]
    complexity = conf["complexity"]
    block_mode = conf["block_mode"]

    if not os.path.isdir(analysis_path):
        os.makedirs(analysis_path)

    # Mode: either block (function) or line granularity
    # Important: Block mode is not supported with network creation
    # https://github.com/gotec/git2net/blob/main/git2net/visualisation.py#L358
    # networks use original_commit_deletion AS pre_commit, but this column is 'not available with use_blocks'/None
    main(project, git_repo_path, analysis_path, block_mode, ranges, args.network_mode, complexity)
