#!/bin/bash

# SPDX-FileCopyrightText: 2025 OTH Regensburg, Nicole Hoess <nicole.hoess@othr.de>
# SPDX-License-Identifier: GPL-2.0-only

# Projects to analyse
project_list=(birt
              conductor
              django
              flink
              postgresql
              qemu
              u-boot
              wine)

project_str_list="birt, conductor, django, flink, postgresql, qemu, u-boot, wine"

# For Codeface, the analysis must be carried out in two different
# Docker containers (codeface_joblin and codeface_gote).
project_str_list_joblin="django, postgresql, qemu, u-boot, wine"
project_str_list_gote="birt, conductor, flink"

# This list maps the selected projects to their corresponding study
# in order to reuse the correct data and results directory during analysis.
# If you remove subject projects, make sure that the mapping stays correct.
# For Django, PostgreSQL, QEMU, U-Boot and Wine: joblin_2017
# For Birt, Conductor, Flink: gote_2022
# For Codeface, this list has no effect, as analyses are separated in containers.
study_str_list="gote_2022, gote_2022, joblin_2017, gote_2022, joblin_2017, joblin_2017, joblin_2017, joblin_2017"

# This list selects projects for the comparison plots.
plot_str_list="birt, flink"

# Base paths
base_path=/home/emse
data_path="$base_path"/data
data_network_path="$base_path"/data/gote_2022

# Git path
git_repo_path="$base_path"/data/baseline/git-repos

# Codeface paths
port=3306
cores=8
codeface_tool_path="$base_path"/tools/codeface/snapshot
codeface_data_path="$base_path"/data/foucault_2015/codeface

# git2net paths
git2net_conf_path="$base_path"/tools/git2net/conf
git2net_data_path="$base_path"/data/baseline/git2net

# GrimoireLab paths
grimoire_conf_path="$base_path"/tools/grimoire/conf
grimoire_network_path="$base_path"/data/gote_2022/grimoire

# Kaiaulu paths
kaiaulu_tool_path="$base_path"/tools/kaiaulu/snapshot
kaiaulu_conf_path="$base_path"/tools/kaiaulu/snapshot/conf

# Analysis paths
res_path="$base_path"/results/baseline
plot_path="$base_path"/plot/baseline
log_path="$base_path"/log/baseline
src_path="$base_path"/src
