#!/bin/bash

# SPDX-FileCopyrightText: 2025 OTH Regensburg, Nicole Hoess <nicole.hoess@othr.de>
# SPDX-License-Identifier: GPL-2.0-only

# Projects to analyse
project_list=(angular_js
              ansible
              jenkins
              jquery
              rails)
project_str_list="angular_js, ansible, jenkins, jquery, rails"

# Base path
base_path=/home/emse

# Git path
git_repo_path="$base_path"/data/foucault_2015/git-repos
bug_git_repo_path="$base_path"/data/foucault_2015/bug-git-repos
cloc_git_repo_path="$base_path"/data/foucault_2015/cloc-git-repos

# Reproducibility data path
reproducibility_data_path="$base_path"/original_studies/foucault_2015/vm/turnover_workdir/turnover/working_dir
bug_fix_path="$base_path"/original_studies/foucault_2015/vm/turnover_workdir/bug_fixes.yml

# Codeface paths
port=3306
cores=8
codeface_tool_path="$base_path"/tools/codeface/snapshot
codeface_data_path="$base_path"/data/foucault_2015/codeface

# git2net paths
git2net_conf_path="$base_path"/tools/git2net/conf
git2net_data_path="$base_path"/data/foucault_2015/git2net

# Kaiaulu paths
kaiaulu_tool_path="$base_path"/tools/kaiaulu/snapshot
kaiaulu_raw_data_path="$base_path"/data/foucault_2015/kaiaulu/rawdata
kaiaulu_data_path="$base_path"/data/foucault_2015/kaiaulu/procdata

# GrimoireLab paths
grimoire_data_path="$base_path"/data/foucault_2015/grimoire

# Analysis paths
res_path="$base_path"/results/foucault_2015
plot_path="$base_path"/plot/foucault_2015
log_path="$base_path"/log/foucault_2015
src_path="$base_path"/src
