#!/bin/bash

# SPDX-FileCopyrightText: 2025 OTH Regensburg, Nicole Hoess <nicole.hoess@othr.de>
# SPDX-License-Identifier: GPL-2.0-only

# Projects to analyse
project_list=(django
              ffmpeg
              gcc
              llvm-project
              postgresql
              qemu
              u-boot
              wine)

# Base path
base_path=/home/emse

# Git path
git_repo_path="$base_path"/data/joblin_2017/git-repos

# Codeface paths
port=3306
cores=8
codeface_tool_path="$base_path"/tools/codeface/snapshot
codeface_data_path="$base_path"/data/joblin_2017/codeface

# git2net paths
git2net_conf_path="$base_path"/tools/git2net/conf
git2net_data_path="$base_path"/data/joblin_2017/git2net

# GrimoireLab paths
grimoire_conf_path="$base_path"/tools/grimoire/conf
grimoire_data_path="$base_path"/data/joblin_2017/grimoire

# Kaiaulu paths
kaiaulu_tool_path="$base_path"/tools/kaiaulu/snapshot
kaiaulu_raw_data_path="$base_path"/data/joblin_2017/kaiaulu/rawdata
kaiaulu_data_path="$base_path"/data/joblin_2017/kaiaulu/procdata

# Analysis paths
res_path="$base_path"/results/joblin_2017
plot_path="$base_path"/plot/joblin_2017
log_path="$base_path"/log/joblin_2017
src_path="$base_path"/src
