#!/bin/bash

# SPDX-FileCopyrightText: 2025 OTH Regensburg, Nicole Hoess <nicole.hoess@othr.de>
# SPDX-License-Identifier: GPL-2.0-only

# Base path
base_path=/home/emse

# Analysis paths
plot_path="$base_path"/plot/literature
literature_path="$base_path"/literature/venues/
src_path="$base_path"/src